"""Бизнес-логика редактора команд.

Сервис работает с чистыми данными: списки, словари.
Не знает о Qt и виджетах.
"""


class EditorService:
    """Правила для редактора команд."""

    def __init__(self, config_repo, command_repo,
                 config_service=None):
        """config_service нужен для создания нового cfg.

        Если не передан - ensure_config упадёт при попытке
        создать новый cfg (но обновление существующего работает).
        """
        self.config_repo = config_repo
        self.command_repo = command_repo
        self.config_service = config_service

    # =========== данные ===========

    def all_commands(self):
        """Все команды (режим debug 0 самые полные)."""
        return self.command_repo.all("debug")

    def all_prefixes(self):
        """Все категории команд."""
        return self.command_repo.prefixes()

    def saved_values(self, config_id: int) -> dict:
        """Сохранённые значения cfg в виде {cmd_id: (use, value)}."""
        return {
            row["command_id"]: (row["use_custom"], row["custom_value"])
            for row in self.config_repo.values(config_id)
        }

    # =========== сохранение значений ===========

    def save_values(self, config_id: int, values: list):
        """Массовое сохранение значений.

        values: [(command_id, use_custom, custom_value), ...]
        """
        self.config_repo.save_values_bulk(config_id, values)

    # =========== сборка content ===========

    def collect_content(self, key_values: dict) -> str:
        """Собирает текст cfg из {key_name: value}."""
        lines = [
            "-- [System-Configuration Ver1.0]",
            "-- Attention: This file is generated by the system, "
            "do not modify!",
            "",
        ]
        for key, value in key_values.items():
            lines.append(f'{key} = "{value}"')
        return "\n".join(lines)

    # =========== создание / обновление cfg ===========

    def ensure_config(self, config_id: int | None,
                      server_id: int | None,
                      filename: str,
                      content: str) -> int:
        """Гарантирует, что cfg существует.

        Если config_id is None 0 создаёт новый через ConfigService.
        Иначе 0 обновляет содержимое.
        Возвращает итоговый config_id.
        """
        if config_id is None:
            if self.config_service is None:
                raise RuntimeError(
                    "EditorService: config_service не задан, "
                    "нельзя создать новый cfg."
                )
            if server_id is None:
                raise ValueError("server_id не задан для нового cfg.")
            return self.config_service.create_from_content(
                server_id, filename, content
            )

        self.config_repo.update(config_id, content)
        return config_id

    # =========== логи ===========

    def write_logs(self, config_id: int, changes: list):
        """Пишет изменившиеся значения в историю.

        changes: [(key_name, old_value, new_value), ...]
        """
        for key, old, new in changes:
            self.config_repo.log_change(config_id, key, old, new)