"""Генератор seed_commands.sql из списка команд.

Запуск из корня проекта:
    python scripts/generate_seed.py

Создаёт: database/seed_commands.sql
Содержит: все команды Aion с описаниями (гибрид: конкретные + по префиксу).
"""
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_PATH = os.path.join(BASE_DIR, "database", "seed_commands.sql")


# ==================== СПИСОК КОМАНД ====================
# Формат: "key_name" - только имя.
# Описания подставляются автоматически: конкретные или по префиксу.

ALL_COMMANDS = [
    # --- g_ (общие игровые) ---
    "g_2dDamage", "g_2dDamageCri", "g_2dDamageCriT2", "g_2dDamageMargin",
    "g_2dDamageOffset", "g_2dDamageR", "g_2dDamageSize", "g_2dDamageSize2",
    "g_2dDamageT1", "g_2dDamageT2", "g_2dDamageT3", "g_2dDamageT4",
    "g_battleCamActive", "g_battleCamRadius", "g_battleCamSmallR",
    "g_battleCamWeight", "g_battleCamWeightNear",
    "g_cam_key_rot", "g_cam_p_max", "g_cam_p_min", "g_cam_rot_ratio",
    "g_camera_cheat", "g_camMax", "g_camMid", "g_camMin", "g_camOffsetZ",
    "g_camStep", "g_captureIME", "g_cfg_version",
    "g_cfg_video_BACKGROUND", "g_cfg_video_ENTITY_DIST", "g_cfg_video_ENV_TEX",
    "g_cfg_video_FSAA", "g_cfg_video_GENERAL", "g_cfg_video_GLARE",
    "g_cfg_video_GLOW", "g_cfg_video_MODEL_CACHE", "g_cfg_video_screen_res",
    "g_cfg_video_SHADER", "g_cfg_video_SHADOW", "g_cfg_video_SKILLFX",
    "g_cfg_video_TERRAIN_DIST", "g_cfg_video_TEXTURE", "g_cfg_video_WATER",
    "g_cfg_video_WEATHER", "g_chainSkillChangeCooltimeDelay",
    "g_chainSkillIndicateDelay", "g_char_manager", "g_charCustomColor",
    "g_CharRotateSpeed", "g_chatlog", "g_CheckDeadServer", "g_damage_blend",
    "g_deathCamActive", "g_deathCamDist", "g_deathCamSpeedFO",
    "g_deathCamSpeedP", "g_deathCamSpeedZ", "g_desolveEnd", "g_desolveStart",
    "g_disperse_loading", "g_EffectPriorityDistance", "g_fall_height",
    "g_falx", "g_faly", "g_falz", "g_fatx", "g_faty", "g_fatz",
    "g_favx", "g_favy", "g_favz", "g_fheight", "g_fireCamOffset",
    "g_fireCamSpeed", "g_gameFlags", "g_gameReplay", "g_gameReplayControl",
    "g_gameReplayName", "g_gameReplaySpeed", "g_ggAuth", "g_headCamDegree",
    "g_headCamDist", "g_headCamStiff", "g_hide", "g_hide_ui",
    "g_hit_freeze", "g_hit_freeze_time", "g_hitCamActive", "g_hitCamShake",
    "g_hitCamShakeReduce", "g_hitFxMonsterSize", "g_IDDreScoreAlarm",
    "g_idle002_time", "g_IDLF1ScoreAlarm", "g_IgnoreUICoolTime",
    "g_maxFov", "g_maxfps", "g_midFov", "g_minFov", "g_MP_fixed_timestep",
    "g_observe", "g_pathfinding", "g_Render", "g_save_preset",
    "g_scaled_attack", "g_scaled_attack_limit", "g_select_server",
    "g_send_level_version", "g_show_breath", "g_show_create_btn",
    "g_show_stunned", "g_showDamageMsg", "g_showFps", "g_showMacroMsg",
    "g_showPanningCursor", "g_targetMarkerType", "g_targetSound",
    "g_tempPseudoFullscreen", "g_test", "g_testFxcSpawn", "g_testIntersect",
    "g_testPut", "g_testRecvWorld", "g_testTeleport", "g_ThirdPersonRange",
    "g_thrust_time", "g_ui_filter", "g_ui_font", "g_ui_scale",
    "g_ui_scale_factor", "g_ui_stillview", "g_ui_tile", "g_uiContour",
    "g_UIForTuning", "g_uiFX", "g_var1", "g_var2", "g_var3", "g_var4",
    "g_verbose", "g_verbose_animation", "g_walkCamActive", "g_walkCamAmp",
    "g_walkCamFreq", "g_weapon_scale", "g_windBox",
    # дополнительные из старого дампа
    "g_draw_3dView", "g_draw_radar", "g_spf", "g_country_code",
    "g_create_info", "g_fmode", "g_freefly", "g_fjump",
    "g_fullscreen", "g_NoWarFog", "g_glide", "g_fly_height",
    "g_auto_disconnect", "g_rotate_speed", "g_rotate_speed_mouse",
    "g_tutorialReset", "g_player_nameid", "g_player_armor",
    "g_player_armor_color", "g_player_face", "g_player_hair",
    "g_player_skin_color", "g_player_hair_color", "g_player_body_scales",
    "g_player_speed", "g_player_pos", "g_player_camera_shake",
    "g_player_fx", "g_smooth_move", "g_blade_fx", "g_blade_time",
    "g_blade_tex", "g_clear_attack_count", "g_client_var",
    "g_program_damage", "g_blend1", "g_blend2", "g_mxID",
    "g_player_scale", "g_player_listener_pos", "g_player_listener_height",
    "g_sound_min_dist", "g_sound_max_dist", "g_blend_time",
    "g_blendout_time", "g_autoZoom", "g_autoZoomDegree", "g_autoZoomSpeed",
    "g_npcCamPosRatio", "g_npcCamPosDist", "g_npcCamAngleZ",
    "g_npcCamAngleX", "g_npcCamRange", "g_npcCamSpeedP", "g_npcCamZ",
    "g_npcCamFov", "g_transCamStiffness", "g_open_aion_web",
    "g_enableGameEffect", "g_enableSkillVoice", "g_showDamageMsg",
    "g_ammoHeightRatio", "g_gore", "g_testPutUser", "g_testRecvWorld",
    "g_clbone", "g_useRotateAnimation", "g_charCustomColor",
    "g_BlendSpine", "g_2dDamageR", "g_AutoWalkType",
    # --- r_ (render) ---
    "r_AccurateParticles", "r_Beams", "r_BumpSelfShadow",
    "r_Char_AmbientColor_Amount", "r_Char_SunColor_Amount",
    "r_Character_Debug", "r_Character_LOD_Bias", "r_Character_NoAnim",
    "r_Character_NoDeform", "r_Character_NoPhys",
    "r_Character_Shadow_Volume", "r_checkSunVis", "r_DebugLights",
    "r_DebugScreenEffects", "r_DecalTextures", "r_depth_buffer",
    "r_DepthBits", "r_DetailDefault", "r_DetailDistance",
    "r_DetailNumLayers", "r_DetailScale", "r_DetailTextures",
    "r_DisableSfx", "r_DisplayInfo", "r_EfMultiTex", "r_EMBM",
    "r_FadeAmount", "r_FSAA", "r_FSAA_quality", "r_FSAA_samples",
    "r_Gamma", "r_GeomInstancing", "r_GetScreenShot",
    "r_HDRBrightOffset", "r_HDRBrightThreshold", "r_HDRDebug",
    "r_HDRFake", "r_HDRLevel", "r_HDRRendering", "r_HeatHaze",
    "r_HeatMapMips", "r_HeatMapSave", "r_HeatSize", "r_HeatType",
    "r_Height", "r_HWLights", "r_LightSourcesAsHeatSources",
    "r_MaximizeWindow", "r_MaxTexLodBias", "r_MeasureOverdraw",
    "r_NightMapSave", "r_NightSize", "r_NightType",
    "r_OceanHeightScale", "r_OceanLodDist", "r_OceanMaxSplashes",
    "r_OceanRendType", "r_OceanSectorSize", "r_OceanSplashScale",
    "r_OceanTexUpdate", "r_OffsetBump", "r_OffsetBumpForce",
    "r_RainMapSize", "r_RB_Merge", "r_ReloadShaders", "r_RenderMode",
    "r_ReplaceCubemap", "r_ResetScreenFx", "r_RestoreLeft",
    "r_RestoreTop", "r_Scissor", "r_ScopeLens_fx", "r_ScreenRefract",
    "r_SelfRefract", "r_SelfShadow", "r_ShaderDefault",
    "r_ShaderDetailObjectsBending", "r_ShaderInfo", "r_ShaderModel",
    "r_ShadersPrecache", "r_ShadersSave", "r_ShaderTerrainDOT3",
    "r_ShaderTerrainSpecular", "r_shadow_maps_debug", "r_ShadowBlur",
    "r_ShadowType", "r_Shininess", "r_ShowLight", "r_ShowLines",
    "r_ShowNormals", "r_ShowOnlyShader", "r_ShowTangents",
    "r_ShowTexTimeGraph", "r_ShowTimeGraph", "r_ShowVideoMemoryStats",
    "r_SM2XPATH", "r_SM30PATH", "r_SSE", "r_SubSurfaceType",
    "r_SunStyleCoronas", "r_SupportCompressedTextures",
    "r_SupportPalettedTextures", "r_TexBindMode", "r_TexBumpQuality",
    "r_TexBumpResolution", "r_TexForceSquare", "r_TexGrayOverage",
    "r_TexHWDXTCompression", "r_TexHWMipsGeneration", "r_TexLMResolution",
    "r_TexLoadMipmapForce", "r_TexMaxSize", "r_TexMinSize",
    "r_TexNormalMapCompressed", "r_TexNormalMapType", "r_TexProcedures",
    "r_TexQuality", "r_TexQuantizeDither", "r_TexResolution",
    "r_TexSimpleMips", "r_TexSkyQuality", "r_TexSkyResolution",
    "r_Texture_Anisotropic_Level", "r_TexturesBaseMip",
    "r_TexturesPixelSize", "r_TexturesStreaming",
    "r_TexturesStreamingOnlyVideo", "r_TexturesStreamingSync",
    "r_TexturesStreamPoolSize", "r_texUnloadDelay",
    "r_Vegetation_Debug", "r_Vegetation_IgnoreVertColors",
    "r_Vegetation_PerpixelLight", "r_VegetationSpritesAlphaBlend",
    "r_VegetationSpritesNoBend", "r_VPFog", "r_VSync",
    "r_Water_Distance_Far", "r_WaterBeachRefractions",
    "r_WaterReflections", "r_WaterReflections_MaxViewDist",
    "r_WaterRefractions", "r_WaterUpdateDeltaAngle",
    "r_WaterUpdateDistance", "r_WaterUpdateFactor", "r_WaveScale",
    "r_Width", "r_WindowHeight", "r_WindowWidth",
    # --- e_ (engine) ---
    "e_active_shadow_maps_receving", "e_bboxes", "e_beach", "e_bflyes",
    "e_capture_file_format", "e_capture_folder", "e_capture_frames",
    "e_cbuffer", "e_ccgf_load", "e_ccgf_make_if_not_found",
    "e_cgf_cache", "e_cgf_load_lods",
    "e_check_number_of_physicalized_polygons", "e_debug_lights",
    "e_debug_rndenv", "e_debug_shaders", "e_debug_shaders_offset",
    "e_decals", "e_decals_life_time_scale",
    "e_decals_neighbor_max_life_time", "e_decals_offset",
    "e_decals_test", "e_deformable_terrain", "e_detail_objects",
    "e_detail_texture", "e_detail_texture_min_fov",
    "e_detail_texture_quality", "e_disable_fx_preprocess",
    "e_disable_fx_process", "e_disable_watercubemap",
    "e_display_musiczone_info", "e_editor_time_ratio",
    "e_game_slopeview", "e_gametime_control_manual",
    "e_geomorph_enable", "e_geomorph_enable_test", "e_geomorph_renderer",
    "e_hires_screenshoot", "e_light_maps", "e_light_maps_exportVersion",
    "e_light_maps_occlusion", "e_light_maps_quality", "e_materials",
    "e_max_entity_lights", "e_max_shadow_map_size",
    "e_maxdistance_enable", "e_maxdistance_entities",
    "e_maxdistance_ratio_entities", "e_maxdistance_terrain",
    "e_new_object_xml", "e_obj_load_dist_ratio", "e_obj_lod_ratio",
    "e_obj_min_view_dist", "e_obj_view_dist_ratio", "e_objects",
    "e_objects_draw_range", "e_objects_fade_on_distance",
    "e_occlusion_volumes", "e_particles", "e_particles_cull",
    "e_particles_debug", "e_particles_debug_spawntest",
    "e_particles_debug_string", "e_particles_debug_type",
    "e_Particles_Draw_Area", "e_Particles_Draw_Box",
    "e_Particles_Draw_Range", "e_particles_freeze",
    "e_particles_fullfx", "e_particles_info", "e_particles_lod",
    "e_particles_max_count", "e_particles_receive_shadows",
    "e_particles_showemitter_name", "e_particles_showonly",
    "e_particles_spawn_distance_ratio", "e_particles_system_only",
    "e_particles_use_partice_table", "e_rain_amount", "e_rain_particle",
    "e_register_in_sectors", "e_scissor_debug",
    "e_sequence_debug_playtime", "e_sequence_debug_spawntime",
    "e_sequence_debug_string", "e_sequence_info", "e_shadow_maps",
    "e_shadow_maps_color_ratio", "e_shadow_maps_debug",
    "e_shadow_maps_fade_from_light_bit",
    "e_shadow_maps_from_static_objects", "e_shadow_maps_frustums",
    "e_shadow_maps_max_casters_per_object", "e_shadow_maps_receiving",
    "e_shadow_maps_self_shadowing", "e_shadow_maps_size_ratio",
    "e_shadow_maps_view_dist_ratio", "e_shadow_spots",
    "e_simple_shadow_maps", "e_SupportLightmaps", "e_terrain",
    "e_terrain_debug", "e_terrain_draw_this_sector_adjacency",
    "e_terrain_draw_this_sector_only", "e_terrain_lod_ratio",
    "e_terrain_log", "e_terrain_merge_far_sectors",
    "e_terrain_occlusion_culling",
    "e_terrain_occlusion_culling_precision",
    "e_terrain_sector_grid", "e_terrain_shadow_index",
    "e_terrain_single_pass", "e_terrain_single_pass_vol_fog",
    "e_terrain_specular", "e_terrain_texture_bind",
    "e_terrain_texture_mip_offset", "e_terrain_texture_mipmaps",
    "e_terrain_texture_pool", "e_TerrainSectorsInfo",
    "e_time_env_enable", "e_time_profiling", "e_time_smoothing",
    "e_timedemo_frames", "e_timedemo_milliseconds", "e_vegetation",
    "e_vegetation_3donly", "e_vegetation_bending",
    "e_vegetation_debug", "e_vegetation_min_size",
    "e_vegetation_plants1_distance", "e_vegetation_sprites",
    "e_vegetation_sprites_distance_ratio",
    "e_vegetation_sprites_min_distance",
    "e_vegetation_sprites_slow_switch",
    "e_vegetation_sprites_texres",
    "e_vegetation_update_shadow_every_frame", "e_water_ocean",
    "e_water_ocean_sun_reflection", "e_water_ocean_tesselation",
    "e_water_render_cull_terrain", "e_water_render_distance",
    "e_water_volumes", "e_weather_change_immediate",
    "e_weather_change_speed", "e_weather_cutscene",
    "e_weather_enable", "e_weather_fx_enable", "e_widescreen",
    # --- p_ (physics) ---
    "p_accuracy_LCPCG", "p_accuracy_LCPCG_no_improvement",
    "p_accuracy_MC", "p_characterik", "p_characterik_arm",
    "p_damping_group_size", "p_decalLifetime", "p_fixed_timestep",
    "p_GEB_max_cells", "p_head_camera", "p_limit_simple_solver_energy",
    "p_list_active_objects", "p_max_contact_gap",
    "p_max_contact_gap_player", "p_max_contact_gap_simple",
    "p_max_contacts", "p_max_LCPCG_fruitless_iters",
    "p_max_LCPCG_iters", "p_max_LCPCG_microiters",
    "p_max_LCPCG_microiters_final", "p_max_LCPCG_subiters",
    "p_max_LCPCG_subiters_final", "p_max_MC_iters",
    "p_max_plane_contacts", "p_max_plane_contacts_distress",
    "p_max_player_velocity", "p_max_substeps", "p_max_unproj_vel",
    "p_max_velocity", "p_max_world_step", "p_min_LCPCG_improvement",
    "p_min_separation_speed", "p_penalty_scale",
    "p_single_step_mode", "p_time_granularity",
    "p_waterbob_mindepth", "p_waterbob_pitch",
    "p_waterbob_pitchspeed", "p_waterbob_roll",
    "p_waterbob_rollspeed",
    # --- es_ (entity system) ---
    "es_bboxes", "es_CamHeight", "es_CamHeightNear", "es_CamRestoreStiff",
    "es_charArmIK_Range", "es_charIK_Range", "es_CharZOffsetSpeed",
    "es_DebugTimer", "es_DisplayInfo", "es_EnableCloth",
    "es_FxSystemRVRLevel", "es_helpers", "es_HitCharacters",
    "es_HitDeadBodies", "es_ImpulseScale", "es_LODShaderDistance",
    "es_LODShaderStep", "es_MaxImpulseAdjMass", "es_MinImpulseVel",
    "es_OnDemandPhysics", "es_PiercingCamera", "es_SplashThreshold",
    "es_SplashTimeout", "es_UpdateAI", "es_UpdateBonePositions",
    "es_UpdateCamera", "es_UpdateCollision",
    "es_UpdateCollisionScript", "es_UpdateContainer",
    "es_UpdateCoocooEgg", "es_UpdateEntities",
    "es_UpdateInvisibleCharacter", "es_UpdatePhysics",
    "es_UpdateScript", "es_UpdateTimer", "es_VisCheckForUpdate",
    # --- ca_ (character / animation) ---
    "ca_ac_cos", "ca_ac_hcos", "ca_ac_hsin",
    "ca_ambient_light_intensity", "ca_ambient_light_range",
    "ca_AnimationDeferredLoad", "ca_AnimationUnloadCheckPerFrame",
    "ca_AnimationUnloadDelay", "ca_AnimationUnloadMaxPerFrame",
    "ca_AnimDisplacementThreshold", "ca_AnimDistanceThreshold",
    "ca_AnimIFrame", "ca_AnimWarningLevel", "ca_BoneAnimUFM",
    "ca_BoundZOffset", "ca_cb_iteration", "ca_ClothMode",
    "ca_CustomColorHair", "ca_CustomColorSkin", "ca_DeathBlendTime",
    "ca_Debug", "ca_DebugHeatSources", "ca_DebugInfo",
    "ca_DebugShaders", "ca_DecalAntiflickerHack",
    "ca_DecalSizeMultiplier", "ca_DefaultDecalTexture",
    "ca_DisableAnimEvents", "ca_DisablePlusRotationMask",
    "ca_DisplayInfo", "ca_drag", "ca_DrawAnims", "ca_DrawBBox",
    "ca_DrawBBoxSub", "ca_DrawBones", "ca_DrawDecalOutline",
    "ca_DrawLHelpers", "ca_edge_max", "ca_edge_min",
    "ca_EnableAnimationLog", "ca_EnableCCG",
    "ca_EnableCharacterShadowVolume", "ca_EnableCubicBlending",
    "ca_EnableDecals", "ca_EnableLightUpdate",
    "ca_EnableTangentSkinning", "ca_EnableVertexColors",
    "ca_fixed_time", "ca_HairAnim", "ca_HairAnimBackPlaneOffset",
    "ca_HairAnimDamping1", "ca_HairAnimDamping2",
    "ca_HairAnimDistance", "ca_HairAnimGravity1", "ca_HairAnimGravity2",
    "ca_HairAnimLimitAngle", "ca_HairAnimMassInc",
    "ca_HairAnimRelaxationIterCount", "ca_horz_edge", "ca_Iteration",
    "ca_KeepMaxCacheSize", "ca_KeepMaxCacheSize2",
    "ca_KeepMaxCacheSize3", "ca_KeepModels", "ca_KeepOrthoUniform",
    "ca_LimitShadowLOD", "ca_LodBias", "ca_LogAnimation",
    "ca_MatPlusDebug", "ca_MatPlusDebug2", "ca_MaxMorphDist",
    "ca_MinVertexWeightLOD0", "ca_MinVertexWeightLOD1",
    "ca_MinVertexWeightLOD2", "ca_MorphNormals", "ca_NoAnim",
    "ca_NoDeform", "ca_NoDraw", "ca_NoDrawBound",
    "ca_NoDrawShadowVolumes", "ca_NoMatPlus", "ca_NoMatPlus2",
    "ca_NoMorph", "ca_NoMtlSorting", "ca_NoPhys",
    "ca_NormalizeBases", "ca_NoTransScale", "ca_OverrideLayer",
    "ca_PerforatingDecals", "ca_PrebuildShadowConnectivity",
    "ca_Profile", "ca_RainPower", "ca_RestartBehaviour",
    "ca_RuntimeScale", "ca_SafeReskin", "ca_ShadowBufferLimit",
    "ca_ShadowDoubleBuffer", "ca_ShadowVolumeExtent",
    "ca_SkinBasedBBoxMask", "ca_SkipBoneAnim", "ca_SSEEnable",
    "ca_SSEEnable1", "ca_SSEEnable2", "ca_StopDeformingAfter",
    "ca_StripifyGeometry", "ca_TangentBasisCalcPeriod",
    "ca_TestMirror", "ca_TestSkinningRepeats", "ca_TickVersion",
    "ca_UpdateSpeed", "ca_UpdateSpeed0", "ca_UpdateSpeed1",
    "ca_UpdateSpeed2", "ca_UpdateSpeed3", "ca_UpdateSpeed4",
    "ca_UseCustomColor", "ca_UseLowestLOD",
    "ca_VertsPerTangSubskin", "ca_ZDeleteConstructionData",
    # --- con_ (console) ---
    "con_auto_complete", "con_disable_console",
    "con_display_last_messages", "con_line_buffer_size",
    # --- CV_ (debug visualization) ---
    "CV_ind_DrawBorderEdges", "CV_ind_ReverseShadowVolumes",
    "CV_ind_VisualizeShadowVolumes",
    # --- d3d9_ ---
    "d3d9_AllowSoftware", "d3d9_ClipPlanes",
    "d3d9_CompressedTextures", "d3d9_DecalOffset", "d3d9_Device",
    "d3d9_ForceSoftware", "d3d9_MipProcedures", "d3d9_NoDepthMaps",
    "d3d9_NodeviceId", "d3d9_NormalMapScale", "d3d9_NV30_PS20",
    "d3d9_NVPerfHUD", "d3d9_Occlusion_Query",
    "d3d9_PalettedTextures", "d3d9_pip_buff_size", "d3d9_rb_Tris",
    "d3d9_rb_Verts", "d3d9_ResetDeviceAfterLoading",
    "d3d9_SaveDepthmaps", "d3d9_SquareTextures", "d3d9_TexMipFilter",
    "d3d9_Texture_Filter_Anisotropic", "d3d9_TextureBits",
    "d3d9_TextureFilter", "d3d9_TripleBuffering", "d3d9_UseBumpmap",
    "d3d9_VBPools", "d3d9_VBPoolSize",
    # --- s_ (sound) ---
    "s_CapsCheck", "s_DebugMusic", "s_DebugSound",
    "s_DebugSoundBuffer", "s_FixedSoundPriority", "s_KeepSound",
    "s_MasterVolume", "s_MaxActiveSoundSpots", "s_MaxHWChannels",
    "s_MaxSoundDist", "s_MinHWChannels", "s_MinRepeatSoundTimeout",
    "s_SampleRate",
    "s_SFXMute_COMMENT_GOSSIP", "s_SFXMute_COMMENT_NPC",
    "s_SFXMute_COMMENT_QUEST", "s_SFXMute_COMMENT_SYSTEM",
    "s_SFXMute_COMMENT_WEATHER", "s_SFXMute_ENV",
    "s_SFXMute_FX", "s_SFXMute_MASTER", "s_SFXMute_UI",
    "s_SFXVolume_COMMENT_GOSSIP", "s_SFXVolume_COMMENT_NPC",
    "s_SFXVolume_COMMENT_QUEST", "s_SFXVolume_COMMENT_SYSTEM",
    "s_SFXVolume_ENV", "s_SFXVolume_FX", "s_SFXVolume_UI",
    "s_SFXVolume_WEATHER", "s_VisAreasPropagation",
    # --- sys_ (system) ---
    "sys_AdaptiveCharLOD", "sys_AdaptiveCharLOD_FF", "sys_affinity",
    "sys_firstlaunch", "sys_fixedframe", "sys_fixedframe_target",
    "sys_noupdate", "sys_PakLogMissingFiles", "sys_PakPriority",
    "sys_PakReadSlice", "sys_script_debugger",
    "sys_skiponlowspec", "sys_spec", "sys_SSInfo",
    "sys_StreamCallbackTimeBudget", "sys_StreamCompressionMask",
    "sys_warnings",
    # --- i_ (input) ---
    "i_direct_input",
    # --- log_ ---
    "log_FileVerbosity", "log_IncludeTime", "log_linefilter",
    "log_Verbosity",
    # --- mov_ ---
    "mov_NoCutscenes", "movie_fontRatio",
    # --- profile ---
    "profile", "profile_filter", "profile_graph",
    "profile_graphScale", "profile_network", "profile_pagefaults",
    "profile_peak",
    # --- Mem ---
    "MemInfo", "MemStats", "MemStatsMaxDepth", "MemStatsThreshold",
    # --- misc ---
    "ExitOnQuit", "fixed_time_step", "f_FTKerning",
    # ==================== Дополнение из реального system.cfg ====================
    # Сеть / VoIP
    "net_blaze_voip_enable", "net_blaze_voip_enable_ptt",
    "net_blaze_voip_playback_volume",
    # Система
    "sys_budget_videomem", "sys_budget_sysmem", "sys_MaxThreads",
    "sys_DisableCrashDialog", "sys_EnableAsserts", "sys_WarningDisable",
    "sys_64bitCache", "sys_DeactivateConsole", "sys_EnableAsserts",
    "sys_FixedFrame", "sys_job_system_enable", "sys_LowSpecPak",
    "sys_main_CPU", "sys_maxFPS", "sys_MaxFps", "sys_physics_CPU",
    "sys_physics_GPU", "sys_preload", "sys_spec_Environment",
    "sys_spec_GameEffects", "sys_spec_light", "sys_spec_ObjectDetail",
    "sys_spec_Particles", "sys_spec_Physics", "sys_spec_PostProcessing",
    "sys_spec_Quality", "sys_spec_Shading", "sys_spec_Shadows",
    "sys_spec_Sound", "sys_spec_Texture", "sys_spec_TextureResolution",
    "sys_spec_VolumetricEffects", "sys_WarningDisable", "sys_WER",
    # Логи
    "log_IgnoreWarnings", "log_Silence",
    # Direct3D9
    "d3d9_PSforce11", "d3d9_VS30", "d3d9_VSforce11",
    "d3d9_AllowSoftware", "d3d9_pip_buff_size", "d3d9_VBPoolSize",
    # Render / Batching
    "r_BatchType", "r_Batching", "r_MaterialsBatching",
    "r_3dvision_bubbleshadow", "r_aionshadow_adaptive",
    "r_aionshadow_blur", "r_aionshadow_obj_size",
    "r_aionshadow_tex_height", "r_AntialiasingMode",
    "r_Brightness", "r_CharacterLODBias", "r_ChromaticAberration",
    "r_ColorBits", "r_ColorGrading", "r_DeferredShadingAmbientLights",
    "r_DepthOfField", "r_Detail", "r_DrawNearFOV", "r_DrawNearZRange",
    "r_DynTexAtlasCloudsMaxSize", "r_DynTexAtlasSpritesMaxSize",
    "r_DynTexMaxSize", "r_EnhanceImage", "r_EnvCMResolution",
    "r_EnvCMupdateInterval", "r_EnvLightCMSize", "r_EnvTexResolution",
    "r_EnvTexUpdateInterval", "r_FlaresTessellationRatio",
    "r_FogShadows", "r_FullscreenPreemption",
    "r_FullScreenHeight", "r_FullScreenWidth",
    "r_HDRBloomRatio", "r_HDRBrightLevel", "r_HDRGrainAmount",
    "r_LodBias", "r_MeshPrecache", "r_MotionBlur",
    "r_mrt_depthrender", "r_mrt_initdetect", "r_MSAA", "r_MultiGPU",
    "r_ParticlesHalfRes", "r_ParticlesHalfResBlendMode",
    "r_ParticlesMotionBlur", "r_ParticlesTessellation",
    "r_PostAA", "r_PostAAEdgeFilter", "r_PostProcessEffects",
    "r_PostProcessEffectsGameFx", "r_PostProcessFilters",
    "r_PostProcessGameFx", "r_ProcFlares", "r_PseudoFullscreen",
    "r_Quality_BumpMapping", "r_rain", "r_Sharpening",
    "r_ShadowJittering", "r_ssao", "r_ssdo", "r_SSReflections",
    "r_StencilBits", "r_sunshafts", "r_SyncVBuf",
    "r_TexMaxAnisotropy", "r_TextureStreaming",
    "r_TexturesStreamingSkipMips", "r_TexturesWarmup",
    "r_ui_shading", "r_UseParticlesHalfResForce",
    "r_UseParticlesMerging", "r_UseParticlesRefraction",
    "r_UseSoftParticles", "r_VegetationSpritesTexRes",
    "r_VolumetricFog", "r_WaterCaustics", "r_WaterGodRays",
    # Effects
    "e_area_merging_distance", "e_AutoPrecacheCgf", "e_CharLodMin",
    "e_CullVegActivation", "e_DecalsAllowGameDecals",
    "e_DecalsLifeTimeScale", "e_Dissolve", "e_DynamicLights",
    "e_effect_quality", "e_ent_view_dist_ratio", "e_fog",
    "e_GI", "e_GsmCache", "e_GsmLodsNum",
    "e_HwOcclusionCullingObjects", "e_HwOcclusionCullingparticles",
    "e_HwOcclusionCullingVegetation", "e_HwOcclusionCullingWater",
    "e_hw_occlusion_culling_water", "e_jukebox_movie_enable",
    "e_level", "e_LodCompMaxSize", "e_LodMin", "e_LodMinTtris",
    "e_LodsForceUse", "e_MaxViewDistSpecLerp",
    "e_nodraw_terrain_shadow", "e_OcclusionCullingViewDistRatio",
    "e_optimized_render_object", "e_ObjQuality",
    "e_ParticlesDiffCM", "e_ParticlesForceSoftParticles",
    "e_ParticlesGI", "e_ParticlesMaxDrawScreen",
    "e_ParticlesMaxScreenFill", "e_ParticlesMinDrawPixels",
    "e_ParticlesObjectCollisions", "e_ParticlesPreload",
    "e_ParticlesQuality", "e_ParticlesShadows", "e_ParticlesThread",
    "e_precache_level", "e_PrecacheLevel", "e_PreloadMaterials",
    "e_PrepareDeformableObjectsAtLoadTime", "e_proc_vegetation",
    "e_Recursion", "e_recursion_occlusion_culling", "e_Render",
    "e_shadows", "e_skip_terrain_culling", "e_SkyBox",
    "e_SkyQuality", "e_SkyType", "e_StatObjBufferRenderTasks",
    "e_StatObjPreload", "e_streamCgf", "e_sun", "e_TerrainAo",
    "e_TerrainLodRatio", "e_TerrainOcclusionCullingMaxDist",
    "e_TerrainTextureLodRatio", "e_TerrainTextureLodRatioBias",
    "e_use_backup_shader", "e_use_terrain_shadow_light",
    "e_VegetationBending", "e_VegetationMinSize",
    "e_vegetation_static_instancing", "e_VegetationSprites",
    "e_VegetationSpritesBatching",
    "e_VegetationSpritesDistanceCustomRatioMin",
    "e_VegetationSpritesDistanceatioMin",
    "e_VegetationUseTerrainColor", "e_ViewDistRatio",
    "e_ViewDistRatioCustom", "e_ViewDistRatioDetail",
    "e_ViewDistRatioLights", "e_ViewDistRatioVegetation",
    "e_view_dist_ratio", "e_view_dist_ratio_detail",
    "e_view_dist_ratio_vegetation", "e_view_dist_vegetation",
    "e_water_ocean_soft_particles", "e_wind", "e_waterocean",
    # Animation
    "ac_animErrorClamp", "ac_clampTimeAnimation", "ac_clampTimeEntity",
    "ac_disableFancyTransitions",
    "ca_CharLodMin", "ca_MemoryDefragEnabled", "ca_PrecacheAnimationSets",
    "ca_ShareVertex", "ca_UseAnimationsCache", "ca_UseFacialAnimation",
    "ca_UsePhysics", "ca_disable_thread", "ca_lod_force", "ca_lod_ratio",
    "ca_thread",
    # AI
    "ai_AmbientFireEnable", "ai_AmbientFireQuota",
    "ai_AmbientFireUpdateInterval", "ai_DebugDrawAmbientFire",
    # Input
    "i_dinputkeys", "i_flashlight_has_fog_volume",
    "i_mouse_accel", "i_mouse_inertia", "i_mouse_smooth",
    "i_precache", "iThreaded", "i_particleeffects",
    "i_rejecteffects", "i_iceeffects",
    # Physics / Quality shaders
    "p_lightrange", "q_ShaderGeneral", "q_ShaderPostProcess",
    "q_ShaderTerrain", "q_ShaderVegetation", "con_restricted",
    # Прочие g_*
    "g_aionHeapSize", "g_fxLevel", "g_gpu_particle_physics",
    "g_loadSlotState", "g_muteMyPet", "g_OBS_volume",
    "g_openSpecialServerList", "g_playerprofile", "g_radialBlur",
    "g_reconnectable", "g_screenshot_preset_path",
    "g_showUIActionMsg", "g_teleportUIDelay",
    "g_ui_interpolation_id", "g_ui_interpolation_type",
    "g_ui_shadow", "g_ui_siegewarfare_option", "g_ui_tile_type",
    "g_useTransitionAnimation", "g_video_GLOW",
    "gpu_particle_physics",
    # HUD / Debug
    "hud_debug", "hud_startpaused", "PriorityThreshold",
# ==================== MRT-профили (единственная крупная группа) ====================
    "g_cfg_video_MRT_BACKGROUND",
    "g_cfg_video_MRT_BUMP",
    "g_cfg_video_MRT_CAMERA",
    "g_cfg_video_MRT_DOF",
    "g_cfg_video_MRT_EFFECT",
    "g_cfg_video_MRT_ENTITY_DIST",
    "g_cfg_video_MRT_ENV_TEX",
    "g_cfg_video_MRT_FSAA",
    "g_cfg_video_MRT_GENERAL",
    "g_cfg_video_MRT_GLARE",
    "g_cfg_video_MRT_GLOW",
    "g_cfg_video_MRT_LOWEST",
    "g_cfg_video_MRT_MODEL_CACHE",
    "g_cfg_video_MRT_SHADER",
    "g_cfg_video_MRT_SHADOW",
    "g_cfg_video_MRT_SKILLFX",
    "g_cfg_video_MRT_SUNSHAFT",
    "g_cfg_video_MRT_TERRAIN_DIST",
    "g_cfg_video_MRT_TEXTURE",
    "g_cfg_video_MRT_WATER",
    "g_cfg_video_MRT_WEATHERLAYER",
    "g_cfg_video_EFFECT",

    # ==================== Звук / музыка (частично) ====================
    "s_BatterySave_Enable",
    "s_FormatSampleRate",
    "s_HRTFEnable",
    "s_MusicIgnoreGameStatus",
    "s_MusicMute",
    "s_MusicPlayOnce",
    "s_MusicVolume",
    "s_NCPing_Enable",
    "s_PriorityThreshold",
    "s_spec_Shading",
    "ss_MusicMute",
]


# ==================== ОПИСАНИЯ ДЛЯ ИЗВЕСТНЫХ КОМАНД ====================
KNOWN_DESCRIPTIONS = {
    # Графика / рендер
    "r_Width": "Ширина окна/экрана",
    "r_Height": "Высота окна/экрана",
    "r_FSAA": "Полноэкранное сглаживание (FSAA)",
    "r_FSAA_samples": "Количество сэмплов сглаживания",
    "r_FSAA_quality": "Качество сглаживания",
    "r_Texture_Anisotropic_Level": "Уровень анизотропной фильтрации (1–16)",
    "r_VSync": "Вертикальная синхронизация",
    "r_Gamma": "Гамма-коррекция",
    "r_ShadowBlur": "Размытие теней",
    "r_ShadowType": "Тип теней",
    "r_HDRRendering": "HDR-рендеринг",
    "r_HDRFake": "Псевдо-HDR",
    "r_HDRLevel": "Уровень HDR",
    "r_WaterReflections": "Отражения в воде",
    "r_WaterRefractions": "Преломления в воде",
    "r_WaterReflections_MaxViewDist": "Максимальная дистанция отражений",
    "r_TexMaxSize": "Максимальный размер текстур",
    "r_TexMinSize": "Минимальный размер текстур",
    "r_TexQuality": "Качество текстур",
    "r_TexturesStreaming": "Потоковая загрузка текстур",
    "r_TexturesStreamPoolSize": "Размер пула текстур",
    "r_ShaderModel": "Модель шейдеров (2.0, 3.0)",
    "r_DetailTextures": "Детальные текстуры",
    "r_DetailDistance": "Дистанция детальных текстур",
    "r_GeomInstancing": "Геометрический инстансинг",
    "r_SSE": "Использование SSE-инструкций",
    "r_MaximizeWindow": "Разворачивать окно на весь экран",
    "r_WindowWidth": "Ширина окна (оконный режим)",
    "r_WindowHeight": "Высота окна (оконный режим)",

    # Direct3D9
    "d3d9_TripleBuffering": "Тройная буферизация (даёт прирост производительности)",
    "d3d9_TextureFilter": "Трилинейная фильтрация",
    "d3d9_Texture_Filter_Anisotropic": "Анизотропная фильтрация D3D9",
    "d3d9_CompressedTextures": "Сжатые текстуры D3D9",
    "d3d9_PalettedTextures": "Палитровые текстуры",
    "d3d9_SquareTextures": "Квадратные текстуры",
    "d3d9_UseBumpmap": "Использовать bump-карты",
    "d3d9_ForceSoftware": "Принудительно программный рендеринг",
    "d3d9_AllowSoftware": "Разрешить программный рендеринг",
    "d3d9_Occlusion_Query": "Запросы окклюзии",
    "d3d9_VBPools": "Пулы вершинных буферов",
    "d3d9_VBPoolSize": "Размер пула вершинных буферов",

    # Движок
    "e_shadow_maps": "Карты теней",
    "e_shadow_maps_size_ratio": "Соотношение размера карт теней",
    "e_shadow_maps_view_dist_ratio": "Дистанция видимости теней",
    "e_shadow_maps_debug": "Отладка карт теней",
    "e_shadow_maps_receiving": "Получение теней объектами",
    "e_shadow_maps_self_shadowing": "Самозатенение объектов",
    "e_particles": "Частицы (вкл/выкл)",
    "e_particles_max_count": "Максимальное количество частиц",
    "e_particles_lod": "LOD частиц",
    "e_objects_fade_on_distance": "Затухание объектов на расстоянии",
    "e_objects_draw_range": "Дистанция отрисовки объектов",
    "e_obj_lod_ratio": "Соотношение LOD объектов",
    "e_obj_view_dist_ratio": "Дистанция видимости объектов",
    "e_terrain": "Ландшафт (вкл/выкл)",
    "e_terrain_lod_ratio": "LOD ландшафта",
    "e_terrain_specular": "Зеркальность ландшафта",
    "e_terrain_texture_mipmaps": "Mipmap ландшафта",
    "e_vegetation": "Растительность",
    "e_vegetation_bending": "Изгиб растительности от ветра",
    "e_vegetation_sprites": "Спрайты растительности",
    "e_vegetation_sprites_distance_ratio": "Дистанция спрайтов растительности",
    "e_water_ocean": "Океан",
    "e_water_ocean_tesselation": "Тесселяция океана",
    "e_water_ocean_sun_reflection": "Отражение солнца на воде",
    "e_water_render_distance": "Дистанция отрисовки воды",
    "e_weather": "Погода",
    "e_weather_enable": "Погодные эффекты",
    "e_weather_fx_enable": "FX-эффекты погоды",
    "e_rain_amount": "Количество дождя",
    "e_rain_particle": "Частицы дождя",
    "e_widescreen": "Широкоэкранный режим",
    "e_detail_texture": "Детальные текстуры",
    "e_detail_texture_quality": "Качество детальных текстур",
    "e_max_shadow_map_size": "Максимальный размер карты теней",
    "e_max_entity_lights": "Максимум источников света",
    "e_maxdistance_enable": "Максимальная дальность прорисовки",
    "e_maxdistance_terrain": "Дальность прорисовки ландшафта",
    "e_maxdistance_entities": "Дальность прорисовки сущностей",
    "e_occlusion_volumes": "Окклюзионные объёмы",
    "e_light_maps": "Карты освещения",
    "e_light_maps_quality": "Качество карт освещения",

    # Персонаж / анимации
    "ca_ambient_light_intensity": "Интенсивность ambient-света на персонаже",
    "ca_ambient_light_range": "Дальность ambient-света",
    "ca_EnableCubicBlending": "Кубическое смешивание (улучшает качество графики)",
    "ca_ClothMode": "Режим ткани (плащи, робы)",
    "ca_DeathBlendTime": "Время анимации смерти",
    "ca_HairAnim": "Анимация волос",
    "ca_HairAnimDamping1": "Демпфирование волос (1)",
    "ca_HairAnimDamping2": "Демпфирование волос (2)",
    "ca_HairAnimGravity1": "Гравитация волос (1)",
    "ca_HairAnimGravity2": "Гравитация волос (2)",
    "ca_UseCustomColor": "Использовать кастомный цвет",
    "ca_CustomColorHair": "Кастомный цвет волос",
    "ca_CustomColorSkin": "Кастомный цвет кожи",

    # Console
    "con_auto_complete": "Автодополнение команд в консоли",
    "con_disable_console": "Отключить внутриигровую консоль (PauseBreak)",
    "con_display_last_messages": "Показывать последние сообщения консоли",
    "con_line_buffer_size": "Размер буфера строк консоли",

    # Звук
    "s_MasterVolume": "Общая громкость",
    "s_MaxSoundDist": "Максимальная дистанция звука",
    "s_SampleRate": "Частота дискретизации",
    "s_MaxHWChannels": "Максимум аппаратных каналов",
    "s_MinHWChannels": "Минимум аппаратных каналов",
    "s_MaxActiveSoundSpots": "Максимум активных источников звука",
    "s_SFXVolume_FX": "Громкость эффектов",
    "s_SFXVolume_ENV": "Громкость окружения",
    "s_SFXVolume_UI": "Громкость интерфейса",
    "s_SFXVolume_WEATHER": "Громкость погоды",
    "s_SFXMute_MASTER": "Отключить весь звук",
    "s_SFXMute_FX": "Отключить звуки эффектов",
    "s_SFXMute_UI": "Отключить звуки интерфейса",

    # Система
    "sys_spec": "Уровень системных требований (1–4)",
    "sys_affinity": "Привязка потоков к ядрам CPU",
    "sys_firstlaunch": "Первый запуск (флаг)",
    "sys_fixedframe": "Фиксированный FPS",
    "sys_skiponlowspec": "Пропускать при низких характеристиках",

    # Игровые
    "g_maxfps": "Максимальный FPS (0 — без лимита)",
    "g_showFps": "Показывать счётчик FPS",
    "g_fullscreen": "Полноэкранный режим",
    "g_ui_scale": "Масштаб интерфейса",
    "g_ui_scale_factor": "Пользовательский множитель масштаба UI",
    "g_ui_font": "Шрифт интерфейса",
    "g_open_aion_web": "Открывать сайт Aion при выходе",
    "g_save_preset": "Сохранять пресеты настроек",
    "g_select_server": "Всегда показывать выбор сервера",
    "g_chatlog": "Логирование чата",
    "g_hide_ui": "Скрыть интерфейс",
    "g_hide": "Скрыть модель персонажа",
    "g_showDamageMsg": "Показывать сообщения урона",
    "g_showMacroMsg": "Показывать отладку макросов",
    "g_gore": "Кровь и расчленение",
    "g_enableGameEffect": "Игровые эффекты",
    "g_enableSkillVoice": "Голосовые реплики скиллов",
    "g_weapon_scale": "Масштаб оружия",
    "g_show_breath": "Показывать дыхание",
    "g_show_stunned": "Показывать оглушение",
    "g_camera_cheat": "Чит-режим камеры",
    "g_camMin": "Минимальная дистанция камеры",
    "g_camMax": "Максимальная дистанция камеры",
    "g_camMid": "Средняя дистанция камеры",
    "g_minFov": "Минимальный угол обзора",
    "g_maxFov": "Максимальный угол обзора",
    "g_autoZoom": "Автоприближение камеры",
    "g_battleCamActive": "Камера в бою",
    "g_deathCamActive": "Камера при смерти",
    "g_walkCamActive": "Тряска камеры при ходьбе",
    "g_hitCamActive": "Тряска камеры при попадании",
    "g_freefly": "Чит-код полёта",
    "g_testTeleport": "Авто-телепорт (чит)",
    "g_ggAuth": "Использовать GameGuard",
    "g_char_manager": "Управление персонажем",
    "g_maxFov": "Максимальный FOV",
    "g_noWarFog": "Отключить военный туман",

    # Физика
    "p_decalLifetime": "Время жизни декалей (следов)",
    "p_fixed_timestep": "Фиксированный шаг физики",
    "p_max_contacts": "Максимум контактов",
    "p_max_player_velocity": "Максимальная скорость игрока",
    "p_waterbob_pitch": "Покачивание камеры в воде (pitch)",
    "p_waterbob_roll": "Покачивание камеры в воде (roll)",
    "p_head_camera": "Камера от головы",

    # Logs
    "log_Verbosity": "Уровень детализации логов",
    "log_FileVerbosity": "Уровень логов в файле",
    "log_IncludeTime": "Добавлять время в лог",
    "log_linefilter": "Фильтр строк лога",

    # Movies
    "mov_NoCutscenes": "Отключить катсцены",
    "movie_fontRatio": "Соотношение шрифта в видео",

    # Profile
    "profile": "Профилирование (вкл/выкл)",
    "profile_graph": "График профилирования",
    "profile_network": "Профиль сети",
    "profile_peak": "Пиковые значения",

    # Memory
    "MemInfo": "Информация о памяти",
    "MemStats": "Статистика памяти",
    "MemStatsThreshold": "Порог статистики памяти",

    # Misc
    "ExitOnQuit": "Выход при завершении",
    "fixed_time_step": "Фиксированный шаг времени",

    # ==================== Дополнение ====================
    # Сеть / VoIP
    "net_blaze_voip_enable": "VoIP в Blaze (голосовой чат)",
    "net_blaze_voip_enable_ptt": "VoIP push-to-talk (кнопка разговора)",
    "net_blaze_voip_playback_volume": "Громкость воспроизведения VoIP",

    # Система
    "sys_budget_videomem": "Бюджет видеопамяти (МБ)",
    "sys_budget_sysmem": "Бюджет системной памяти (МБ)",
    "sys_MaxThreads": "Максимальное количество потоков CPU",
    "sys_DisableCrashDialog": "Отключить диалог краша",
    "sys_EnableAsserts": "Включить asserts",
    "sys_WarningDisable": "Отключить предупреждения",
    "sys_64bitCache": "64-битный кеш",
    "sys_DeactivateConsole": "Отключить консоль",
    "sys_FixedFrame": "Фиксированный кадр",
    "sys_job_system_enable": "Включить job-систему",
    "sys_LowSpecPak": "Пак для слабых ПК",
    "sys_main_CPU": "Ядро CPU для главного потока",
    "sys_maxFPS": "Максимальный FPS (системный)",
    "sys_MaxFps": "Максимальный FPS",
    "sys_physics_CPU": "Ядро для физики",
    "sys_physics_GPU": "GPU для физики",
    "sys_preload": "Предзагрузка ресурсов",
    "sys_skiponlowspec": "Пропускать на слабых системах",
    "sys_spec_Environment": "Уровень качества окружения",
    "sys_spec_GameEffects": "Уровень игровых эффектов",
    "sys_spec_light": "Уровень освещения",
    "sys_spec_ObjectDetail": "Уровень детализации объектов",
    "sys_spec_Particles": "Уровень частиц",
    "sys_spec_Physics": "Уровень физики",
    "sys_spec_PostProcessing": "Уровень постобработки",
    "sys_spec_Quality": "Общий уровень качества",
    "sys_spec_Shading": "Уровень шейдинга",
    "sys_spec_Shadows": "Уровень теней",
    "sys_spec_Sound": "Уровень звука",
    "sys_spec_Texture": "Уровень текстур",
    "sys_spec_TextureResolution": "Разрешение текстур",
    "sys_spec_VolumetricEffects": "Объёмные эффекты",
    "sys_WER": "Windows Error Reporting",
    "sys_SSInfo": "Информация о суперсэмплинге",
    "sys_StreamCallbackTimeBudget": "Бюджет времени стриминга (мкс)",
    "sys_StreamCompressionMask": "Маска сжатия стриминга",
    "sys_warnings": "Системные предупреждения",

    # Логи
    "log_IgnoreWarnings": "Игнорировать предупреждения в логе",
    "log_Silence": "Полностью отключить лог",

    # Direct3D9
    "d3d9_PSforce11": "Принудительно использовать Pixel Shader 1.1",
    "d3d9_VS30": "Вершинные шейдеры 3.0",
    "d3d9_VSforce11": "Принудительно использовать Vertex Shader 1.1",
    "d3d9_AllowSoftware": "Разрешить программный рендеринг",
    "d3d9_pip_buff_size": "Размер pipeline-буфера",
    "d3d9_VBPoolSize": "Размер пула вершинных буферов",

    # Render
    "r_BatchType": "Тип батчинга",
    "r_Batching": "Батчинг",
    "r_MaterialsBatching": "Батчинг материалов",
    "r_3dvision_bubbleshadow": "Тени для NVIDIA 3D Vision",
    "r_aionshadow_adaptive": "Адаптивные тени Aion",
    "r_aionshadow_blur": "Размытие теней Aion",
    "r_aionshadow_obj_size": "Размер объектов для теней Aion",
    "r_aionshadow_tex_height": "Высота текстуры теней Aion",
    "r_AntialiasingMode": "Режим антиалиасинга",
    "r_Brightness": "Яркость",
    "r_CharacterLODBias": "LOD-смещение персонажа",
    "r_ChromaticAberration": "Хроматическая аберрация",
    "r_ColorBits": "Битность цвета",
    "r_ColorGrading": "Цветокоррекция",
    "r_DeferredShadingAmbientLights": "Ambient-освещение в deferred shading",
    "r_DepthOfField": "Глубина резкости",
    "r_Detail": "Детализация",
    "r_DrawNearFOV": "FOV для ближней отрисовки",
    "r_DrawNearZRange": "Z-диапазон ближней отрисовки",
    "r_DynTexAtlasCloudsMaxSize": "Максимальный размер атласа облаков",
    "r_DynTexAtlasSpritesMaxSize": "Максимальный размер атласа спрайтов",
    "r_DynTexMaxSize": "Максимальный размер динамических текстур",
    "r_EnhanceImage": "Улучшение изображения",
    "r_EnvCMResolution": "Разрешение cubemap окружения",
    "r_EnvCMupdateInterval": "Интервал обновления cubemap",
    "r_EnvLightCMSize": "Размер light cubemap окружения",
    "r_EnvTexResolution": "Разрешение текстур окружения",
    "r_EnvTexUpdateInterval": "Интервал обновления текстур окружения",
    "r_FlaresTessellationRatio": "Тесселяция бликов",
    "r_FogShadows": "Тени от тумана",
    "r_FullscreenPreemption": "Приоритет полноэкранного режима",
    "r_FullScreenWidth": "Ширина fullscreen",
    "r_FullScreenHeight": "Высота fullscreen",
    "r_HDRBloomRatio": "Соотношение HDR-свечения",
    "r_HDRBrightLevel": "Уровень яркости HDR",
    "r_HDRGrainAmount": "Зернистость HDR",
    "r_LodBias": "Смещение LOD",
    "r_MeshPrecache": "Предзагрузка мешей",
    "r_MotionBlur": "Размытие в движении",
    "r_mrt_depthrender": "Рендер глубины MRT",
    "r_mrt_initdetect": "Определение MRT при инициализации",
    "r_MSAA": "Мультисэмплинг MSAA",
    "r_MultiGPU": "Поддержка нескольких GPU",
    "r_ParticlesHalfRes": "Полу-разрешение частиц",
    "r_ParticlesHalfResBlendMode": "Режим блендинга half-res частиц",
    "r_ParticlesMotionBlur": "Motion blur для частиц",
    "r_ParticlesTessellation": "Тесселяция частиц",
    "r_PostAA": "Постобработка антиалиасинга",
    "r_PostAAEdgeFilter": "Фильтр краёв пост-AA",
    "r_PostProcessEffects": "Постпроцессинг эффектов",
    "r_PostProcessEffectsGameFx": "Постпроцессинг игровых FX",
    "r_PostProcessFilters": "Фильтры постобработки",
    "r_PostProcessGameFx": "Постпроцессинг GameFX",
    "r_ProcFlares": "Процедурные блики",
    "r_PseudoFullscreen": "Псевдо-полноэкранный режим",
    "r_Quality_BumpMapping": "Качество bump-mapping",
    "r_rain": "Дождь",
    "r_Sharpening": "Резкость",
    "r_ShadowJittering": "Джиттеринг теней",
    "r_ssao": "SSAO (ambient occlusion)",
    "r_ssdo": "SSDO",
    "r_SSReflections": "Screen-space reflections",
    "r_StencilBits": "Битность stencil-буфера",
    "r_sunshafts": "Солнечные лучи (god rays)",
    "r_SyncVBuf": "Синхронизация вершинного буфера",
    "r_TexMaxAnisotropy": "Максимум анизотропной фильтрации",
    "r_TextureStreaming": "Потоковая загрузка текстур",
    "r_TexturesStreamingSkipMips": "Пропускать mip-уровни при стриминге",
    "r_TexturesWarmup": "Прогрев текстур",
    "r_ui_shading": "Шейдинг UI",
    "r_UseParticlesHalfResForce": "Форсировать half-res частиц",
    "r_UseParticlesMerging": "Объединение частиц",
    "r_UseParticlesRefraction": "Рефракция частиц",
    "r_UseSoftParticles": "Мягкие частицы",
    "r_VegetationSpritesTexRes": "Разрешение спрайтов растительности",
    "r_VolumetricFog": "Объёмный туман",
    "r_WaterCaustics": "Каустика воды",
    "r_WaterGodRays": "God rays на воде",

    # Engine / Effects
    "e_area_merging_distance": "Дистанция объединения зон",
    "e_AutoPrecacheCgf": "Автопредзагрузка CGF",
    "e_CharLodMin": "Минимальный LOD персонажа",
    "e_CullVegActivation": "Активация отсечения растительности",
    "e_DecalsAllowGameDecals": "Разрешить игровые декали",
    "e_DecalsLifeTimeScale": "Масштаб времени жизни декалей",
    "e_Dissolve": "Растворение объектов",
    "e_DynamicLights": "Динамические источники света",
    "e_effect_quality": "Качество эффектов",
    "e_ent_view_dist_ratio": "Дистанция видимости сущностей",
    "e_fog": "Туман",
    "e_GI": "Global Illumination",
    "e_GsmCache": "Кеш GSM-теней",
    "e_GsmLodsNum": "Количество LOD GSM",
    "e_HwOcclusionCullingObjects": "HW-отсечение объектов",
    "e_HwOcclusionCullingparticles": "HW-отсечение частиц",
    "e_HwOcclusionCullingVegetation": "HW-отсечение растительности",
    "e_HwOcclusionCullingWater": "HW-отсечение воды",
    "e_hw_occlusion_culling_water": "HW-отсечение воды (старое)",
    "e_jukebox_movie_enable": "Включить видео-джукбокс",
    "e_level": "Уровень",
    "e_LodCompMaxSize": "Максимальный размер LOD-компонента",
    "e_LodMin": "Минимальный LOD",
    "e_LodMinTtris": "Мин. треугольников для LOD",
    "e_LodsForceUse": "Форсировать использование LOD",
    "e_MaxViewDistSpecLerp": "Макс. дистанция интерполяции вида",
    "e_nodraw_terrain_shadow": "Не рисовать тень ландшафта",
    "e_OcclusionCullingViewDistRatio": "Дистанция occlusion culling",
    "e_optimized_render_object": "Оптимизация рендер-объектов",
    "e_ObjQuality": "Качество объектов",
    "e_ParticlesDiffCM": "Diffuse cubemap для частиц",
    "e_ParticlesForceSoftParticles": "Форсировать мягкие частицы",
    "e_ParticlesGI": "Global Illumination для частиц",
    "e_ParticlesMaxDrawScreen": "Макс. размер частиц на экране",
    "e_ParticlesMaxScreenFill": "Макс. заполнение экрана частицами",
    "e_ParticlesMinDrawPixels": "Мин. размер частиц в пикселях",
    "e_ParticlesObjectCollisions": "Коллизии частиц с объектами",
    "e_ParticlesPreload": "Предзагрузка частиц",
    "e_ParticlesQuality": "Качество частиц",
    "e_ParticlesShadows": "Тени от частиц",
    "e_ParticlesThread": "Поток для частиц",
    "e_precache_level": "Уровень предзагрузки",
    "e_PrecacheLevel": "Уровень предзагрузки",
    "e_PreloadMaterials": "Предзагрузка материалов",
    "e_PrepareDeformableObjectsAtLoadTime": "Подготовка деформируемых объектов при загрузке",
    "e_proc_vegetation": "Процедурная растительность",
    "e_Recursion": "Рекурсия",
    "e_recursion_occlusion_culling": "Рекурсивное occlusion culling",
    "e_Render": "Рендер",
    "e_shadows": "Тени",
    "e_skip_terrain_culling": "Пропустить отсечение ландшафта",
    "e_SkyBox": "Небесный куб",
    "e_SkyQuality": "Качество неба",
    "e_SkyType": "Тип неба",
    "e_StatObjBufferRenderTasks": "Буфер задач рендера статических объектов",
    "e_StatObjPreload": "Предзагрузка статических объектов",
    "e_streamCgf": "Стриминг CGF",
    "e_sun": "Солнце",
    "e_TerrainAo": "Ambient Occlusion ландшафта",
    "e_TerrainLodRatio": "LOD ландшафта",
    "e_TerrainOcclusionCullingMaxDist": "Макс. дистанция occlusion culling ландшафта",
    "e_TerrainTextureLodRatio": "LOD текстур ландшафта",
    "e_TerrainTextureLodRatioBias": "Смещение LOD текстур ландшафта",
    "e_use_backup_shader": "Использовать запасной шейдер",
    "e_use_terrain_shadow_light": "Тень ландшафта от источника света",
    "e_VegetationBending": "Изгиб растительности",
    "e_VegetationMinSize": "Минимальный размер растительности",
    "e_vegetation_static_instancing": "Static instancing растительности",
    "e_VegetationSprites": "Спрайты растительности",
    "e_VegetationSpritesBatching": "Батчинг спрайтов растительности",
    "e_VegetationSpritesDistanceCustomRatioMin": "Мин. дистанция кастомных спрайтов",
    "e_VegetationSpritesDistanceatioMin": "Мин. дистанция спрайтов",
    "e_VegetationUseTerrainColor": "Цвет растительности от ландшафта",
    "e_ViewDistRatio": "Дистанция видимости",
    "e_ViewDistRatioCustom": "Кастомная дистанция видимости",
    "e_ViewDistRatioDetail": "Дистанция деталей",
    "e_ViewDistRatioLights": "Дистанция видимости источников света",
    "e_ViewDistRatioVegetation": "Дистанция видимости растительности",
    "e_view_dist_ratio": "Дистанция видимости",
    "e_view_dist_ratio_detail": "Дистанция деталей",
    "e_view_dist_ratio_vegetation": "Дистанция растительности",
    "e_view_dist_vegetation": "Дистанция видимости растительности",
    "e_water_ocean_soft_particles": "Мягкие частицы на воде",
    "e_wind": "Ветер",
    "e_waterocean": "Океан",

    # Character Animation
    "ac_animErrorClamp": "Ограничение ошибок анимации",
    "ac_clampTimeAnimation": "Ограничение времени анимации",
    "ac_clampTimeEntity": "Ограничение времени сущности",
    "ac_disableFancyTransitions": "Отключить fancy-переходы",
    "ca_CharLodMin": "Минимальный LOD персонажа",
    "ca_MemoryDefragEnabled": "Дефрагментация памяти",
    "ca_PrecacheAnimationSets": "Предзагрузка наборов анимаций",
    "ca_ShareVertex": "Общие вершины",
    "ca_UseAnimationsCache": "Кеш анимаций",
    "ca_UseFacialAnimation": "Лицевая анимация",
    "ca_UsePhysics": "Физика персонажа",
    "ca_disable_thread": "Отключить поток анимации",
    "ca_lod_force": "Форсировать LOD",
    "ca_lod_ratio": "Соотношение LOD",
    "ca_thread": "Поток для анимации",

    # AI
    "ai_AmbientFireEnable": "Ambient fire (огонь в мире)",
    "ai_AmbientFireQuota": "Квота ambient fire",
    "ai_AmbientFireUpdateInterval": "Интервал обновления ambient fire",
    "ai_DebugDrawAmbientFire": "Отладка ambient fire",

    # Input
    "i_dinputkeys": "DirectInput-клавиши",
    "i_flashlight_has_fog_volume": "Объём тумана у фонаря",
    "i_mouse_accel": "Ускорение мыши",
    "i_mouse_inertia": "Инерция мыши",
    "i_mouse_smooth": "Сглаживание мыши",
    "i_precache": "Предзагрузка ввода",
    "iThreaded": "Потоковый ввод",
    "i_particleeffects": "Эффекты частиц",
    "i_rejecteffects": "Отклонять эффекты",
    "i_iceeffects": "Ледяные эффекты",

    # Physics / Quality
    "p_lightrange": "Дальность света",
    "q_ShaderGeneral": "Общий шейдер",
    "q_ShaderPostProcess": "Шейдер постобработки",
    "q_ShaderTerrain": "Шейдер ландшафта",
    "q_ShaderVegetation": "Шейдер растительности",
    "con_restricted": "Ограниченная консоль",

    # Прочие g_*
    "g_aionHeapSize": "Размер heap Aion",
    "g_fxLevel": "Уровень FX",
    "g_gpu_particle_physics": "Физика частиц на GPU",
    "g_loadSlotState": "Состояние загрузки слота",
    "g_muteMyPet": "Отключить звук питомца",
    "g_OBS_volume": "Громкость OBS",
    "g_openSpecialServerList": "Открыть особый список серверов",
    "g_playerprofile": "Профиль игрока",
    "g_radialBlur": "Радиальное размытие",
    "g_reconnectable": "Возможность переподключения",
    "g_screenshot_preset_path": "Путь скриншотов",
    "g_showUIActionMsg": "Сообщения действий UI",
    "g_teleportUIDelay": "Задержка UI телепорта",
    "g_ui_interpolation_id": "ID интерполяции UI",
    "g_ui_interpolation_type": "Тип интерполяции UI",
    "g_ui_shadow": "Тень UI",
    "g_ui_siegewarfare_option": "Опции осады",
    "g_ui_tile_type": "Тип tile UI",
    "g_useTransitionAnimation": "Анимации переходов",
    "g_video_GLOW": "Свечение (GLOW)",
    "gpu_particle_physics": "Физика частиц на GPU",

    # HUD / Debug
    "hud_debug": "Отладка HUD",
    "hud_startpaused": "HUD на паузе при старте",
    "PriorityThreshold": "Порог приоритета",

    # ==================== MRT-профили ====================
    "g_cfg_video_MRT_BACKGROUND": "MRT-профиль: фон",
    "g_cfg_video_MRT_BUMP": "MRT-профиль: bump-маппинг",
    "g_cfg_video_MRT_CAMERA": "MRT-профиль: камера",
    "g_cfg_video_MRT_DOF": "MRT-профиль: глубина резкости",
    "g_cfg_video_MRT_EFFECT": "MRT-профиль: эффекты",
    "g_cfg_video_MRT_ENTITY_DIST": "MRT-профиль: дистанция сущностей",
    "g_cfg_video_MRT_ENV_TEX": "MRT-профиль: текстуры окружения",
    "g_cfg_video_MRT_FSAA": "MRT-профиль: сглаживание",
    "g_cfg_video_MRT_GENERAL": "MRT-профиль: общий",
    "g_cfg_video_MRT_GLARE": "MRT-профиль: блики",
    "g_cfg_video_MRT_GLOW": "MRT-профиль: свечение",
    "g_cfg_video_MRT_LOWEST": "MRT-профиль: минимальный",
    "g_cfg_video_MRT_MODEL_CACHE": "MRT-профиль: кеш моделей",
    "g_cfg_video_MRT_SHADER": "MRT-профиль: шейдеры",
    "g_cfg_video_MRT_SHADOW": "MRT-профиль: тени",
    "g_cfg_video_MRT_SKILLFX": "MRT-профиль: эффекты скиллов",
    "g_cfg_video_MRT_SUNSHAFT": "MRT-профиль: солнечные лучи",
    "g_cfg_video_MRT_TERRAIN_DIST": "MRT-профиль: дистанция ландшафта",
    "g_cfg_video_MRT_TEXTURE": "MRT-профиль: текстуры",
    "g_cfg_video_MRT_WATER": "MRT-профиль: вода",
    "g_cfg_video_MRT_WEATHERLAYER": "MRT-профиль: погодные слои",
    "g_cfg_video_EFFECT": "Уровень видео-эффектов",

    # ==================== Звук / музыка ====================
    "s_BatterySave_Enable": "Режим энергосбережения (отключает звук при низком заряде)",
    "s_FormatSampleRate": "Частота дискретизации звука (Гц)",
    "s_HRTFEnable": "HRTF (объёмный звук в наушниках)",
    "s_MusicIgnoreGameStatus": "Игнорировать статус игры для музыки",
    "s_MusicMute": "Отключить музыку",
    "s_MusicPlayOnce": "Играть музыку один раз",
    "s_MusicVolume": "Громкость музыки",
    "s_NCPing_Enable": "Пинг NPC-звуков",
    "s_PriorityThreshold": "Порог приоритета звука",
    "s_spec_Shading": "Уровень шейдинга звука (устаревшее)",
    "ss_MusicMute": "Отключить музыку (дубль)",
}


# ==================== ОПИСАНИЯ ПО ПРЕФИКСУ ====================
PREFIX_DESCRIPTIONS = {
    "g_":      "Общий игровой параметр",
    "r_":      "Параметр рендеринга",
    "e_":      "Параметр движка / мира",
    "p_":      "Параметр физики",
    "es_":     "Параметр сущностей",
    "ca_":     "Параметр персонажа / анимации",
    "con_":    "Параметр консоли",
    "CV_":     "Отладочная визуализация",
    "d3d9_":   "Параметр DirectX 9",
    "s_":      "Параметр звука",
    "sys_":    "Системный параметр",
    "i_":      "Параметр ввода",
    "log_":    "Параметр логирования",
    "mov_":    "Параметр видео / катсцен",
    "profile": "Параметр профилирования",
    "Mem":     "Параметр памяти",
    "misc":    "Прочий параметр",
}


# ==================== ОПРЕДЕЛЕНИЕ ПРЕФИКСА ====================

PREFIX_CODES = sorted(PREFIX_DESCRIPTIONS.keys(), key=len, reverse=True)


def detect_prefix(key: str) -> str:
    """Определяет префикс команды. Если не подходит - 'misc'."""
    for code in PREFIX_CODES:
        if key.startswith(code):
            return code
    return "misc"


# ==================== ОПРЕДЕЛЕНИЕ ТИПА ====================

def guess_value_type(key: str) -> str:
    """Угадывает тип значения по имени команды."""
    low = key.lower()

    # int-подобные суффиксы
    int_suffixes = (
        "_size", "_count", "_max", "_min", "_level", "_quality",
        "_bits", "_iter", "_iters", "_idx", "_index", "_num",
        "_frames", "_rate", "_ratio_count", "fps",
    )
    # bool-подобные
    bool_prefixes = ("b_", "is_", "use_", "enable", "disable", "allow", "force")
    bool_keys = {
        "g_fullscreen", "g_showFps", "g_hide", "g_hide_ui",
        "g_camera_cheat", "g_freefly", "g_verbose",
        "r_VSync", "r_TexturesStreaming", "r_DetailTextures",
        "e_particles", "e_terrain", "e_vegetation", "e_water_ocean",
        "con_disable_console",
        "g_select_server", "g_open_aion_web", "g_save_preset",
        "e_shadow_maps", "e_weather_enable",
        "ca_EnableCubicBlending", "ca_ClothMode",
        "sys_fixedframe", "mov_NoCutscenes",
        "g_gore", "g_enableGameEffect",
    }
    # float-подобные
    float_keys = {
        "r_Gamma", "r_FadeAmount", "r_HDRLevel",
        "g_camMin", "g_camMax", "g_camMid", "g_ui_scale",
        "e_terrain_lod_ratio", "e_obj_lod_ratio",
        "p_waterbob_pitch", "p_waterbob_roll",
        "ca_ambient_light_intensity", "ca_ambient_light_range",
        "s_MasterVolume", "s_MaxSoundDist",
    }

    if key in bool_keys:
        return "bool"
    if key in float_keys:
        return "float"
    if any(low.endswith(s) for s in int_suffixes):
        return "int"
    if low.startswith(bool_prefixes):
        return "bool"
    if "_ratio" in low or "_scale" in low or "_amount" in low:
        return "float"
    return "string"


# ==================== ГЕНЕРАЦИЯ SQL ====================

def escape_sql(s: str) -> str:
    return s.replace("'", "''")


def main():
    lines = [
        "-- Aion.CfgStudio — сгенерированный справочник команд",
        "-- Автогенерация: scripts/generate_seed.py",
        f"-- Всего команд: {len(ALL_COMMANDS)}",
        "",
    ]

    # группируем по префиксам
    grouped: dict[str, list[str]] = {}
    for key in ALL_COMMANDS:
        code = detect_prefix(key)
        grouped.setdefault(code, []).append(key)

    # порядок как в PREFIX_DESCRIPTIONS
    order = list(PREFIX_DESCRIPTIONS.keys())

    for code in order:
        keys = grouped.get(code, [])
        if not keys:
            continue

        name = PREFIX_DESCRIPTIONS[code]
        lines.append(f"-- ==================== {code} — {name} ====================")
        lines.append(
            "INSERT OR IGNORE INTO Commands "
            "(key_name, prefix_id, value_type, default_value, "
            "possible_values, min_value, max_value, description, mode) "
            "VALUES"
        )

        rows = []
        for key in keys:
            desc = KNOWN_DESCRIPTIONS.get(key, "")
            if not desc:
                # общее описание по префиксу
                desc = PREFIX_DESCRIPTIONS.get(code, "Параметр")
            vtype = guess_value_type(key)
            desc_sql = escape_sql(desc)
            rows.append(
                f"('{escape_sql(key)}', "
                f"(SELECT id FROM Prefixes WHERE code='{code}'), "
                f"'{vtype}', NULL, NULL, NULL, NULL, "
                f"'{desc_sql}', 'advanced')"
            )

        lines.append(",\n".join(rows) + ";")
        lines.append("")

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Сгенерировано: {OUT_PATH}")
    print(f"Всего команд: {len(ALL_COMMANDS)}")
    for code in order:
        cnt = len(grouped.get(code, []))
        if cnt:
            print(f"  {code:8s} {cnt}")


if __name__ == "__main__":
    main()